### ISSUE TITLE
Server interfere with client router

### ISSUE THREAD

**Issue by ZimGil** [ZimGil/ngWiz#104]
**Describe the bug**
After running the server and opening the browser on it's port (3000), the server will interfere with the client `router` and the user will get an `Cannot GET /path` error

**To Reproduce**
1. Run server (in server dir `npm start`)
2. Browse to `localhost:3000`
3. Refresh

**Expected behavior**
Normal refresh, any other pat `page-not-found works!`

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version 70.0.3538.110

**Comment by ortichon** [comment]
It's not the issue. 
the server should always return the `index.html`. this will solve your problem

**Comment by ZimGil** [comment]
Resolved by #108
